tirpitz_forum/core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.index_view, name='index'),
    path('create/category', views.create_category_view, name='create_category'),
    path('delete/category/<int:pk>', views.delete_category_view, name='delete_category'),
    path('update/category/<int:pk>', views.update_category_view, name='update_category'),
    path('topics/<int:pk>', views.topics_list_view, name='topics'),
    path('register', views.register_view, name='register'),
    path('create/topic/<int:pk>', views.topic_create_view, name='create_topic'),
    path('topics/posts/<int:pk>', views.topics_posts_view, name='topics_posts'),
    path('create/posts/<int:pk>', views.create_post_view, name='create_post'),
]

tirpitz_forum/urls.py
from django.contrib import admin
from django.urls import path, include
from tirpitz_forum import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('tirpitz_forum.core.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tirpitz_forum/core/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MinLengthValidator
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _


def get_or_create_delete():
    """ Get deleted user """
    return User.objects.get_or_create(name='Erased')[0]


class Category(models.Model):
    """ Forum category model """
    name = models.CharField(_('Category name'), max_length=64, validators=[MinLengthValidator(3)])
    order_number = models.PositiveSmallIntegerField(_('Order number'), default=0)

    class Meta:
        """ Meta class """
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')
        ordering = ['-order_number']

    def __str__(self):
        return self.name


class Topic(models.Model):
    """ Topic model """
    name = models.CharField(_('Topic'), max_length=128, validators=[MinLengthValidator(12)])
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(_('Active'), default=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, blank=False, null=True)

    class Meta:
        """ Meta class """
        verbose_name = _('Topic')
        verbose_name_plural = _('Topics')
        ordering = ['-created_at']

    def __str__(self):
        return slugify(self.name)


class Post(models.Model):
    """ Post class """
    text = models.TextField(_('Text'))
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, blank=False, null=False)
    author = models.ForeignKey(User, null=True, blank=False, on_delete=models.SET(get_or_create_delete))

    class Meta:
        """ Meta class """
        verbose_name = _('Post')
        verbose_name_plural = _('Posts')
        ordering = ['created_at']

tirpitz_forum/core/forms.py
""" Forms """
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Category, Topic, Post


class CreateCategoryForm(ModelForm):
    """ Create category form """

    class Meta:
        """ Meta class """
        model = Category
        fields = ['name', 'order_number']


class CreateTopicForm(ModelForm):
    """ Create topic form """

    class Meta:
        """ Meta class """
        model = Topic
        fields = ['name']


class CreatePostForm(ModelForm):
    """ Create post form """

    class Meta:
        """ Meta class """
        model = Post
        fields = ['text']


class RegisterForm(UserCreationForm):
    """ Register user form """

    first_name = forms.CharField(max_length=20, required=False, help_text=_("Optional"))
    last_name = forms.CharField(max_length=30, required=False, help_text=_("Optional"))
    email = forms.EmailField(max_length=128, required=True, help_text=_("Required"))

    class Meta:
        """ Meta class """
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

tirpitz_forum/core/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.db import transaction
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView, FormView, ListView, DeleteView, UpdateView, DetailView
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy
from .forms import CreateCategoryForm, RegisterForm, CreateTopicForm, CreatePostForm
from .models import Category, Topic, Post
from .mixins import SuperUserMixin


class IndexView(ListView):
    """ Index View """
    model = Category
    template_name = "index.html"


class CreateCategoryView(LoginRequiredMixin, SuperUserMixin, SuccessMessageMixin, CreateView):
    """ Add Category View """
    model = Category
    form_class = CreateCategoryForm
    template_name = "create_category.html"
    success_url = reverse_lazy('core:index')
    success_message = _("Category successfully created")


class DeleteCategoryView(LoginRequiredMixin, SuperUserMixin, SuccessMessageMixin, DeleteView):
    """ Delete Category View """
    model = Category
    template_name = "delete_category.html"
    success_url = reverse_lazy('core:index')
    success_message = _("Category successfully deleted")


class UpdateCategoryView(LoginRequiredMixin, SuperUserMixin, SuccessMessageMixin, UpdateView):
    """ Update Category View """
    model = Category
    form_class = CreateCategoryForm
    template_name = "create_category.html"
    success_url = reverse_lazy('core:index')
    success_message = _("Category successfully updated")


class TopicsListView(ListView):
    """ Category List View """
    model = Topic
    template_name = 'topics_list.html'
    paginate_by = 20

    def get_queryset(self):
        """ Override queryset"""
        category_pk = self.kwargs['pk']
        return Topic.objects.filter(category_id=category_pk)

    def get_context_data(self, *, object_list=None, **kwargs):
        """ Override get context data """
        context = super(TopicsListView, self).get_context_data(object_list=object_list, **kwargs)
        context['category'] = Category.objects.get(id=self.kwargs['pk'])
        return context


class TopicCreateView(LoginRequiredMixin, SuccessMessageMixin, FormView):
    """ Topic Create View """
    model = Topic
    form_class = CreateTopicForm
    model_2 = Post
    form_class_2 = CreatePostForm
    template_name = 'create_topic.html'
    success_message = _('Topic created with success')
    success_url = reverse_lazy('core:index')

    def get_context_data(self, *, object_list=None, **kwargs):
        """ Override get context data """
        context = super(TopicCreateView, self).get_context_data(object_list=object_list, **kwargs)
        context['form2'] = self.form_class_2()
        return context

    def post(self, request, *args, **kwargs):
        """ Override post method """
        response = super(TopicCreateView, self).post(request, *args, **kwargs)
        form = self.form_class({'name': request.POST['name']})
        form2 = self.form_class_2({'text': request.POST['text']})

        if form.is_valid() and form2.is_valid():
            with transaction.atomic():
                new_topic = self.model(name=request.POST['name'], category_id=self.kwargs['pk'])
                new_topic.save()

                first_post = self.model_2(text=request.POST['text'], topic=new_topic, author=request.user)
                first_post.save()

            return redirect(self.success_url)

        return render(request, self.template_name, {'form': form, 'form2': form2})


class RegisterView(CreateView):
    """ Register View """
    template_name = 'registration/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('core:index')
    success_message = _("User successfully created")


class TopicPostsView(ListView):
    """ List of posts from topic View """
    model = Post
    template_name = 'topics_posts.html'
    form_class = CreatePostForm
    paginate_by = 20

    def get_queryset(self):
        """ Override queryset"""
        topic_pk = self.kwargs['pk']
        return Post.objects.filter(topic_id=topic_pk)

    def get_context_data(self, *, object_list=None, **kwargs):
        """ Override get context data """
        context = super(TopicPostsView, self).get_context_data(object_list=object_list, **kwargs)
        context['topic'] = Topic.objects.get(id=self.kwargs['pk'])
        context['form'] = self.form_class
        return context


class CreatePostView(LoginRequiredMixin, CreateView):
    """ Create new post by authenticated user View """
    model = Post
    form_class = CreatePostForm
    success_message = _("Post successfully created")

    def get(self, *args, **kwargs):
        """ Override get method """
        return redirect(reverse_lazy('core:topics_posts', kwargs=kwargs))

    def post(self, request, *args, **kwargs):
        """ Override post method """
        form = self.form_class({'text': request.POST['text']})

        if not form.is_valid():
            messages.error(request, _("Incorrect data in post from"))
            return redirect(reverse_lazy('core:topics_posts', kwargs=kwargs))

        post = self.model(text=request.POST['text'], topic_id=kwargs['pk'], author=request.user)
        post.save()

        messages.success(request, self.success_message)
        return redirect(reverse_lazy('core:topics_posts', kwargs=kwargs))


# Create views
index_view = IndexView.as_view()
register_view = RegisterView.as_view()
topics_list_view = TopicsListView.as_view()
topic_create_view = TopicCreateView.as_view()
create_category_view = CreateCategoryView.as_view()
delete_category_view = DeleteCategoryView.as_view()
update_category_view = UpdateCategoryView.as_view()
topics_posts_view = TopicPostsView.as_view()
create_post_view = CreatePostView.as_view()

tirpitz_forum/core/templates/base.html
{% extends 'bootstrap4/bootstrap4.html' %}
{% load bootstrap4 static i18n %}
{% load static %}

<!-- Overwrite page title -->
{% block bootstrap4_title %}{% trans 'Tirpitz Forum' %}{% endblock %}

<!-- Overwrite js extra head -->
{% block bootstrap4_extra_head %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="shortcut icon" href="{% static 'core/img/favicon.png' %}">
{% endblock %}

<!-- Overwrite place before content -->
{% block bootstrap4_before_content %}
    <!-- Overwrite body class -->
    <body class="d-flex flex-column min-vh-100">

    <!-- Great place for menu -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">

        <!-- Website logo and title -->
        <a class="navbar-brand" href="{% url 'core:index' %}">
            <img src="{% static '/core/img/favicon.png' %}" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
            {% trans 'Python Academy Forum' %}
        </a>

        <!-- Mobile menu button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#websiteMainNavbar" aria-controls="websiteMainNavbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Website menu elements -->
        <div class="collapse navbar-collapse" id="websiteMainNavbar">

            <!-- Website menu elements on left -->
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:index' %}">url #1</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:index' %}">url #2</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:index' %}">url #2</a>
                </li>
            </ul>

            <!-- Website menu search -->
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
                        <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
                    </svg>
                </button>
            </form>

            <!-- Website menu user -->
            <ul class="navbar-nav mt-2 mt-lg-0">
                <li class="nav-item dropdown">

                    <!-- User avatar -->
                    <a class="nav-link dropdown-toggle" id="avatarNavbar" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="{% if request.user.is_authenticated %}{% static 'core/img/guest.png' %}{% else %}{% static 'core/img/guest.png' %}{% endif %}"
                             class="border border-primary rounded-circle"
                             alt="{{ user.get_username }}" width="40" height="40">
                    </a>

                    <!-- User avatar actions -->
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="avatarNavbar">
                        {% if request.user.is_authenticated %}
                            <a class="dropdown-item">{{ request.user }}</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'password_change' %}">{% trans 'Change password' %}</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'logout' %}">{% trans 'Logout' %}</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'login' %}">{% trans 'Login' %}</a>
                            <a class="dropdown-item" href="{% url 'core:register' %}">{% trans 'Register' %}</a>
                        {% endif %}
                    </div>
                </li>
            </ul>
        </div>
    </nav>
{% endblock %}

<!-- Page content -->
{% block bootstrap4_content %}
    <div class="container my-4" >
        {% block content %}
        {% endblock %}
    </div>
{% endblock %}

<!-- Overwrite place after content -->
{% block bootstrap4_after_content %}
    <!-- Great place for footer -->
    <footer id="sticky-footer" class="py-4 bg-dark text-white-50 mt-auto">
        <div class="container text-center">
            <small>Copyright {% now 'Y' %} &copy; Your Website</small>
        </div>
    </footer>
    </body>
{% endblock %}

tirpitz_forum/core/templates/create_category.html
{% extends 'base.html' %}
{% load bootstrap4 i18n %}

{% block content %}
    <div class="row">
        <div class="col">
            <form class="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="d-none d-lg-block d-xl-block">
                    {% bootstrap_button _("Save") button_type="submit" button_class="btn btn-primary" %}
                    <a href="{% url 'core:index' %}" class="btn btn-secondary">{% trans 'Cancel' %}</a>
                </div>
                <div class="d-lg-none d-xl-none">
                    {% bootstrap_button _("Save") button_type="submit" button_class="btn btn-primary btn-block" %}
                    <a href="{% url 'core:index' %}" class="btn btn-secondary btn-block">{% trans 'Cancel' %}</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

tirpitz_forum/core/templates/create_topic.html
{% extends 'base.html' %}

{% load bootstrap4 i18n %}

{% block content %}
<div class="row">
    <div class="col">
        <form class="form" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% bootstrap_form form2 %}

                <div class="d-none d-lg-block d-xl-block">
                    {% bootstrap_button _("Create") button_type="submit" button_class="btn btn-primary" %}
                    <a href="{% url 'core:index' %}" class="btn btn-secondary">{% trans 'Cancel' %}</a>
                </div>
                <div class="d-lg-none d-xl-none">
                    {% bootstrap_button _("Create") button_type="submit" button_class="btn btn-primary btn-block" %}
                    <a href="{% url 'core:index' %}" class="btn btn-secondary btn-block">{% trans 'Cancel' %}</a>
                </div>
        </form>
    </div>
</div>
{% endblock %}

tirpitz_forum/core/templates/delete_category.html
{% extends 'base.html' %}
{% load bootstrap4 i18n %}

{% block content %}
    <div class="row">
        <div class="col">
            <form class="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h1>{% blocktrans with name=category.name %}Are you sure you want to delete {{ name }} ?{% endblocktrans %}</h1>

                <div class="d-none d-lg-block d-xl-block">
                    {% bootstrap_button _("Delete") button_type="submit" button_class="btn btn-danger" %}
                    <a href="{% url 'core:index' %}" class="btn btn-secondary">{% trans 'Cancel' %}</a>
                </div>
                <div class="d-lg-none d-xl-none">
                    {% bootstrap_button _("Delete") button_type="submit" button_class="btn btn-danger btn-block" %}
                    <a href="{% url 'core:index' %}" class="btn btn-secondary btn-block">{% trans 'Cancel' %}</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

tirpitz_forum/core/templates/index.html
{% extends 'base.html' %}
{% load bootstrap4 static i18n %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <div class="float-left">
                        {% trans 'Categories' %}
                    </div>
                    {% if user.is_superuser %}
                    <div class="float-right">
                        <a href="{% url 'core:create_category' %}" class="badge badge-success">{% trans 'Create new category' %}</a>
                    </div>
                    {% endif %}
                </div>

                <ul class="list-group list-group-flush">
                    {% if object_list %}
                        {% for category in object_list %}
                            <li class="list-group-item">
                                <div class="float-left">
                                    <a href="{% url 'core:topics' category.pk %}">{{ category.name }}</a>
                                </div>
                                {% if user.is_superuser %}
                                <div class="float-right">
                                    <a class="badge badge-info" href="{% url 'core:update_category' category.pk %}">
                                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"></path>
                                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"></path>
                                        </svg>
                                        {% trans 'Edit' %}
                                    </a>

                                    <a class="badge badge-danger" href="{% url 'core:delete_category' category.pk %}">
                                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-x-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"></path>
                                            <path fill-rule="evenodd" d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"></path>
                                        </svg>
                                        {% trans 'Delete' %}
                                    </a>
                                </div>
                                {% endif %}
                            </li>
                        {% endfor %}
                    {% else %}
                        <li class="list-group-item">{% trans 'No categories' %}</li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

tirpitz_forum/core/templates/topics_list.html
{% extends 'base.html' %}

{% load bootstrap4 i18n %}

{% block content %}
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <div class="float-left">
                        {{ category.name }}
                    </div>
                    <div class="float-right">
                        <a href="{% url 'core:create_topic' category.pk %}" class="badge badge-success">{% trans 'Create new topic' %}</a>
                    </div>
                </div>

                <ul class="list-group list-group-flush">
                    {% if object_list %}
                        {% for topic in page_obj %}
                            <li class="list-group-item">
                                <div class="float-left">
                                    <a href="{% url 'core:topics_posts' topic.pk %}">{{ topic.name }}</a>
                                </div>

                                <div class="float-right">
                                    <!-- placeholder -->
                                </div>
                            </li>
                        {% endfor %}
                    {% else %}
                        <li class="list-group-item">{% trans 'No topics' %}</li>
                    {% endif %}
                </ul>
            </div>
            <div class="pagination justify-content-center mt-4">
                {% bootstrap_pagination page_obj %}
            </div>
        </div>
    </div>
{% endblock %}

tirpitz_forum/core/templates/topics_posts.html
{% extends 'base.html' %}

{% load bootstrap4 i18n %}

{% block content %}
    <div class="row">
        <div class="col">
            <nav class="navbar navbar-light bg-light">
                <a class="navbar-brand">{{ topic.name }}</a>
            </nav>
            {% if object_list %}
                {% for post in page_obj %}
                    <div class="card mt-3">
                        <div class="card-body">
                            <h5 class="card-title">{{ post.author.username }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{% trans 'Created at:' %} {{ post.created_at }} {% if post.updated_at %} | {% trans 'Updated at:' %}  {{ post.updated_at }}{% endif %}</h6>
                            <p class="card-text">{{ post.text }}</p>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <li class="list-group-item">{% trans 'No posts' %}</li>
            {% endif %}

            {% if request.user.is_authenticated %}
            <div class="mt-3">
                <form class="form" method="post" action="{% url 'core:create_post' topic.pk %}"  enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="d-none d-lg-block d-xl-block">
                        {% bootstrap_button _("Save") button_type="submit" button_class="btn btn-primary" %}
                    </div>
                    <div class="d-lg-none d-xl-none">
                        {% bootstrap_button _("Save") button_type="submit" button_class="btn btn-primary btn-block" %}
                    </div>
                </form>
            </div>
            {% endif %}

            <div class="pagination justify-content-center mt-4">
                {% bootstrap_pagination page_obj %}
            </div>
        </div>
    </div>
{% endblock %}